---
- name: Setup Web Server
  hosts: all
  remote_user: root

  tasks:
  - name: Install Apache Server
    apt:
      name: apache2
      state: present
  - name: Install PHP7.4
    apt:
      name: php7.4
      state: present
  - name: Set timezone to Africa/Lagos
    ansible.builtin.timezone:
      name: 'Africa/Lagos'
  - name: Copy index file to the remote server
    copy:
      src: /root/ansible/index.php
      dest: /var/www/html/index.php
      owner: root
      group: root
      mode: 0644